version: '3.1'
services:
  db:
    image: postgres:13
    container_name: botiga
    environment:
      - POSTGRES_DB=botiga
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: django_botiga
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2023_Javier.Gimenez@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: