# Generated by Django 5.1.6 on 2025-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('data_caducitat', models.DateField()),
                ('CVC', models.CharField(max_length=3)),
                ('estat_pagament', models.BooleanField(default=False)),
            ],
        ),
    ]
